### ISSUE TITLE
Change configuration format

### ISSUE THREAD

**Issue by NoUseFreak** [NoUseFreak/letitgo#11]
**Is your feature request related to a problem? Please describe.**
To make internal processes easier and make it more extendable configuration needs to change.

**Describe the solution you'd like**

```yaml
letitgo:
  name: letitgo
  description: LetItGo automates releases.
  actions:
  - type: changelog
  - type: githubrelease
     assets:
     - ./build/pkg/*
  - type: homebrew
    homepage: https://github.com/NoUseFreak/letitgo
    url: https://github.com/NoUseFreak/letitgo/releases/download/{{ .Version }}/darwin_amd64.zip
    tap:
      url: git@github.com:NoUseFreak/homebrew-brew.git
    test: system "#{bin}/{{ .Name }} -h"
```

**Describe alternatives you've considered**
This allows for much easier processing and looping.
