### ISSUE TITLE
Support archiving

### ISSUE THREAD

**Issue by NoUseFreak** [NoUseFreak/letitgo#8]
**Is your feature request related to a problem? Please describe.**
Allow users to let letigto archive the artifacts

```
archive:
  - files:
      - build/*/letitgo
    target: build/pkg/
    extra_files:
      - LICENSE
      - CHANGELOG.md
    mode: zip
```
